general:
  project: minimal-transformer
  seed: 42

trainer:
  num_epochs: 10
  device: cuda

dataset:
  path: .data
  eng_csv_path: eng.csv
  deu_csv_path: deu.csv
  dataset_size: 10000
  sentence_length: 10
  batch_size: 128
  train_test_split: [0.8, 0.2]

model:
  d_model: 256
  num_heads: 8
  num_layers: 2
  dropout: 0.0
  rotary_embedding_dim: 32

optimizer:
  learning_rate: 1e-3